version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    networks:
      - db_network
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres", "-h", "127.0.0.1", "-p", "15432" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  db_network:
